/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package from_pages;

import java.awt.Color;

/**
 *
 * @author DELL
 */
public class Applis_Stagiaire extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Applis_Stagiaire() {
        initComponents();
        
        main.removeAll();
        Accueil home = new Accueil();
        main.add(home).setVisible(true);
        
        if(page_title.getText().equals("Accueil")){
            onglet_tableau.setBackground(new Color(102,204,255));
            text_tb_board.setForeground(Color.white);
        }
        
        if (text_resize.getText().equals("<|||")) {
            sideBar.setVisible(true);
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        onglet_tableau = new javax.swing.JPanel();
        text_tb_board = new javax.swing.JLabel();
        onglet_encadreur = new javax.swing.JPanel();
        text_encadreur = new javax.swing.JLabel();
        onglet_tuteur = new javax.swing.JPanel();
        text_tuteur = new javax.swing.JLabel();
        onglet_stagiaire = new javax.swing.JPanel();
        text_stagiaire = new javax.swing.JLabel();
        onglet_utilisateur = new javax.swing.JPanel();
        text_utilisateur = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        onglet_stage = new javax.swing.JPanel();
        text_stage = new javax.swing.JLabel();
        navBar = new javax.swing.JPanel();
        resize = new javax.swing.JPanel();
        text_resize = new javax.swing.JLabel();
        page_title = new javax.swing.JLabel();
        profil = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        main = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION DES STAGIAIRES");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(219, 219, 219));

        sideBar.setBackground(new java.awt.Color(0, 153, 255));
        sideBar.setForeground(new java.awt.Color(0, 153, 153));
        sideBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sideBarMouseMoved(evt);
            }
        });

        onglet_tableau.setBackground(new java.awt.Color(219, 219, 219));
        onglet_tableau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        onglet_tableau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onglet_tableau.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                onglet_tableauMouseMoved(evt);
            }
        });
        onglet_tableau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onglet_tableauMouseClicked(evt);
            }
        });

        text_tb_board.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text_tb_board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/increase_32.png"))); // NOI18N
        text_tb_board.setText(" Tableau de board");

        javax.swing.GroupLayout onglet_tableauLayout = new javax.swing.GroupLayout(onglet_tableau);
        onglet_tableau.setLayout(onglet_tableauLayout);
        onglet_tableauLayout.setHorizontalGroup(
            onglet_tableauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_tableauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_tb_board, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        onglet_tableauLayout.setVerticalGroup(
            onglet_tableauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_tableauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_tb_board, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        onglet_encadreur.setBackground(new java.awt.Color(219, 219, 219));
        onglet_encadreur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        onglet_encadreur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onglet_encadreur.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                onglet_encadreurMouseMoved(evt);
            }
        });
        onglet_encadreur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onglet_encadreurMouseClicked(evt);
            }
        });

        text_encadreur.setBackground(new java.awt.Color(255, 255, 255));
        text_encadreur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text_encadreur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list_32px.png"))); // NOI18N
        text_encadreur.setText(" Encadreur");

        javax.swing.GroupLayout onglet_encadreurLayout = new javax.swing.GroupLayout(onglet_encadreur);
        onglet_encadreur.setLayout(onglet_encadreurLayout);
        onglet_encadreurLayout.setHorizontalGroup(
            onglet_encadreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_encadreurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_encadreur, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        onglet_encadreurLayout.setVerticalGroup(
            onglet_encadreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onglet_encadreurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_encadreur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        onglet_tuteur.setBackground(new java.awt.Color(219, 219, 219));
        onglet_tuteur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        onglet_tuteur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onglet_tuteur.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                onglet_tuteurMouseMoved(evt);
            }
        });
        onglet_tuteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onglet_tuteurMouseClicked(evt);
            }
        });

        text_tuteur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text_tuteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list_32px.png"))); // NOI18N
        text_tuteur.setText(" Tuteur");

        javax.swing.GroupLayout onglet_tuteurLayout = new javax.swing.GroupLayout(onglet_tuteur);
        onglet_tuteur.setLayout(onglet_tuteurLayout);
        onglet_tuteurLayout.setHorizontalGroup(
            onglet_tuteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_tuteurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_tuteur, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        onglet_tuteurLayout.setVerticalGroup(
            onglet_tuteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onglet_tuteurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_tuteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        onglet_stagiaire.setBackground(new java.awt.Color(219, 219, 219));
        onglet_stagiaire.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        onglet_stagiaire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onglet_stagiaire.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                onglet_stagiaireMouseMoved(evt);
            }
        });
        onglet_stagiaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onglet_stagiaireMouseClicked(evt);
            }
        });

        text_stagiaire.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text_stagiaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list_32px.png"))); // NOI18N
        text_stagiaire.setText(" Stagiaire");

        javax.swing.GroupLayout onglet_stagiaireLayout = new javax.swing.GroupLayout(onglet_stagiaire);
        onglet_stagiaire.setLayout(onglet_stagiaireLayout);
        onglet_stagiaireLayout.setHorizontalGroup(
            onglet_stagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onglet_stagiaireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_stagiaire, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        onglet_stagiaireLayout.setVerticalGroup(
            onglet_stagiaireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_stagiaireLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_stagiaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        onglet_utilisateur.setBackground(new java.awt.Color(219, 219, 219));
        onglet_utilisateur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        onglet_utilisateur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onglet_utilisateur.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                onglet_utilisateurMouseMoved(evt);
            }
        });
        onglet_utilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onglet_utilisateurMouseClicked(evt);
            }
        });

        text_utilisateur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text_utilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list_32px.png"))); // NOI18N
        text_utilisateur.setText(" Utilisateur");

        javax.swing.GroupLayout onglet_utilisateurLayout = new javax.swing.GroupLayout(onglet_utilisateur);
        onglet_utilisateur.setLayout(onglet_utilisateurLayout);
        onglet_utilisateurLayout.setHorizontalGroup(
            onglet_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_utilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        onglet_utilisateurLayout.setVerticalGroup(
            onglet_utilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onglet_utilisateurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel5.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stagiaire");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Logo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        onglet_stage.setBackground(new java.awt.Color(219, 219, 219));
        onglet_stage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        onglet_stage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onglet_stage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                onglet_stageMouseMoved(evt);
            }
        });
        onglet_stage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onglet_stageMouseClicked(evt);
            }
        });

        text_stage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        text_stage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list_32px.png"))); // NOI18N
        text_stage.setText(" Stage");

        javax.swing.GroupLayout onglet_stageLayout = new javax.swing.GroupLayout(onglet_stage);
        onglet_stage.setLayout(onglet_stageLayout);
        onglet_stageLayout.setHorizontalGroup(
            onglet_stageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onglet_stageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_stage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        onglet_stageLayout.setVerticalGroup(
            onglet_stageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_stageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_stage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onglet_stage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onglet_tuteur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onglet_stagiaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onglet_utilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onglet_encadreur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(onglet_tableau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        sideBarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {onglet_encadreur, onglet_stagiaire, onglet_tableau, onglet_tuteur, onglet_utilisateur});

        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(onglet_tableau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(onglet_encadreur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(onglet_tuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(onglet_stagiaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(onglet_stage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(onglet_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        sideBarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {onglet_encadreur, onglet_stagiaire, onglet_tableau, onglet_tuteur, onglet_utilisateur});

        navBar.setBackground(new java.awt.Color(219, 219, 219));
        navBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 255)));
        navBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                navBarMouseMoved(evt);
            }
        });

        resize.setBackground(new java.awt.Color(219, 219, 219));
        resize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resize.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                resizeMouseMoved(evt);
            }
        });
        resize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resizeMouseClicked(evt);
            }
        });

        text_resize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_resize.setText("<|||");
        text_resize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout resizeLayout = new javax.swing.GroupLayout(resize);
        resize.setLayout(resizeLayout);
        resizeLayout.setHorizontalGroup(
            resizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_resize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        resizeLayout.setVerticalGroup(
            resizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_resize, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        page_title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        page_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page_title.setText("Accueil");

        profil.setBackground(new java.awt.Color(255, 255, 255));
        profil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profil.setOpaque(false);
        profil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                profilMouseMoved(evt);
            }
        });
        profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/male_user_32.png"))); // NOI18N
        jLabel3.setText(" Adama DAOU");

        javax.swing.GroupLayout profilLayout = new javax.swing.GroupLayout(profil);
        profil.setLayout(profilLayout);
        profilLayout.setHorizontalGroup(
            profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profilLayout.setVerticalGroup(
            profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addComponent(resize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(page_title, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217)
                .addComponent(profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navBarLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(page_title, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(219, 219, 219));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 153, 255)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Copy-right©-2023");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(main)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1232, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onglet_tableauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_tableauMouseClicked
        // TODO add your handling code here:
        page_title.setText("Accueil");
        main.removeAll();
        Accueil home = new Accueil();
        main.add(home).setVisible(true);
    }//GEN-LAST:event_onglet_tableauMouseClicked

    private void onglet_utilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_utilisateurMouseClicked
        // TODO add your handling code here:
        page_title.setText("Utilisateur");
        main.removeAll();
        Form_Utilisateur us = new Form_Utilisateur();
        main.add(us).setVisible(true);
    }//GEN-LAST:event_onglet_utilisateurMouseClicked

    private void onglet_encadreurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_encadreurMouseClicked
        // TODO add your handling code here:
        page_title.setText("Encadreur");
        main.removeAll();
        Form_Encadreur enc = new Form_Encadreur();
        main.add(enc).setVisible(true);
    }//GEN-LAST:event_onglet_encadreurMouseClicked

    private void onglet_tuteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_tuteurMouseClicked
        page_title.setText("Tuteur");
        main.removeAll();
        Form_Tuteur tt = new Form_Tuteur();
        main.add(tt).setVisible(true);
    }//GEN-LAST:event_onglet_tuteurMouseClicked

    private void onglet_utilisateurMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_utilisateurMouseMoved
        // TODO add your handling code here:
        onglet_utilisateur.setBackground(new Color(102,204,255));
        text_utilisateur.setForeground(Color.white);
    }//GEN-LAST:event_onglet_utilisateurMouseMoved

    private void sideBarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBarMouseMoved
        // TODO add your handling code here:
        onglet_utilisateur.setBackground(new Color(219,219,219));
        text_utilisateur.setForeground(Color.black);
        
        onglet_tableau.setBackground(new Color(219,219,219));
        text_tb_board.setForeground(Color.black);
        
        onglet_stagiaire.setBackground(new Color(219,219,219));
        text_stagiaire.setForeground(Color.black);
        
        onglet_stage.setBackground(new Color(219,219,219));
        text_stage.setForeground(Color.black);
        
        onglet_encadreur.setBackground(new Color(219,219,219));
        text_encadreur.setForeground(Color.black);
        
        onglet_tuteur.setBackground(new Color(219,219,219));
        text_tuteur.setForeground(Color.black);
        
        resize.setBackground(new Color(219,219,219));
        
    }//GEN-LAST:event_sideBarMouseMoved

    private void onglet_tableauMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_tableauMouseMoved
        // TODO add your handling code here:
        onglet_tableau.setBackground(new Color(102,204,255));
        text_tb_board.setForeground(Color.white);
    }//GEN-LAST:event_onglet_tableauMouseMoved

    private void onglet_stagiaireMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_stagiaireMouseMoved
        // TODO add your handling code here:
        onglet_stagiaire.setBackground(new Color(102,204,255));
        text_stagiaire.setForeground(Color.white);
    }//GEN-LAST:event_onglet_stagiaireMouseMoved

    private void onglet_stagiaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_stagiaireMouseClicked
        // TODO add your handling code here:
        page_title.setText("Stagiaire");
        main.removeAll();
        Form_Stagiaire form_st = new Form_Stagiaire();
        main.add(form_st).setVisible(true);
    }//GEN-LAST:event_onglet_stagiaireMouseClicked

    private void onglet_stageMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_stageMouseMoved
        // TODO add your handling code here:
        onglet_stage.setBackground(new Color(102,204,255));
        text_stage.setForeground(Color.white);
    }//GEN-LAST:event_onglet_stageMouseMoved

    private void onglet_stageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_stageMouseClicked
        // TODO add your handling code here:
        page_title.setText("Stage");
        main.removeAll();
       Form_Stage form_stage = new Form_Stage();
        main.add(form_stage).setVisible(true);
        
    }//GEN-LAST:event_onglet_stageMouseClicked

    private void onglet_encadreurMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_encadreurMouseMoved
        // TODO add your handling code here:
        onglet_encadreur.setBackground(new Color(102,204,255));
        text_encadreur.setForeground(Color.white);
    }//GEN-LAST:event_onglet_encadreurMouseMoved

    private void onglet_tuteurMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onglet_tuteurMouseMoved
        // TODO add your handling code here:
        onglet_tuteur.setBackground(new Color(102,204,255));
        text_tuteur.setForeground(Color.white);
    }//GEN-LAST:event_onglet_tuteurMouseMoved

    private void resizeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resizeMouseMoved
        resize.setBackground(new Color(102, 204, 255));
    }//GEN-LAST:event_resizeMouseMoved

    private void resizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resizeMouseClicked
        if (text_resize.getText().equals("<|||")) {
            sideBar.setVisible(false);
            // txt_menu.setText("");
            text_resize.setText("|||>");
        } else {
            //txt_menu.setText("");
            text_resize.setText("<|||");
            sideBar.setVisible(true);
        }
    }//GEN-LAST:event_resizeMouseClicked

    private void profilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_profilMouseMoved

    private void profilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profilMouseClicked

    private void navBarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navBarMouseMoved
        // TODO add your handling code here:
        resize.setBackground(new Color(219,219,219));
    }//GEN-LAST:event_navBarMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Applis_Stagiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Applis_Stagiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Applis_Stagiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Applis_Stagiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Applis_Stagiaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JDesktopPane main;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel onglet_encadreur;
    private javax.swing.JPanel onglet_stage;
    private javax.swing.JPanel onglet_stagiaire;
    private javax.swing.JPanel onglet_tableau;
    private javax.swing.JPanel onglet_tuteur;
    private javax.swing.JPanel onglet_utilisateur;
    private javax.swing.JLabel page_title;
    private javax.swing.JPanel profil;
    private javax.swing.JPanel resize;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel text_encadreur;
    private javax.swing.JLabel text_resize;
    private javax.swing.JLabel text_stage;
    private javax.swing.JLabel text_stagiaire;
    private javax.swing.JLabel text_tb_board;
    private javax.swing.JLabel text_tuteur;
    private javax.swing.JLabel text_utilisateur;
    // End of variables declaration//GEN-END:variables
}
