/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package from_pages;

/**
 *
 * @author DELL
 */
public class Registre extends javax.swing.JInternalFrame {

    /**
     * Creates new form Registre
     */
    public Registre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        case_head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        case_name = new javax.swing.JPanel();
        champ_prenom = new javax.swing.JLabel();
        champ_user = new javax.swing.JLabel();
        champ_password = new javax.swing.JLabel();
        champ_conf_pass = new javax.swing.JLabel();
        champ_name = new javax.swing.JLabel();
        case_password = new javax.swing.JTextField();
        case_prenom = new javax.swing.JTextField();
        case_names = new javax.swing.JTextField();
        case_pass_confir = new javax.swing.JTextField();
        case_user = new javax.swing.JTextField();
        compte_creat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        case_head.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("GESTION DES REGISTRES");

        javax.swing.GroupLayout case_headLayout = new javax.swing.GroupLayout(case_head);
        case_head.setLayout(case_headLayout);
        case_headLayout.setHorizontalGroup(
            case_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(case_headLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(499, Short.MAX_VALUE))
        );
        case_headLayout.setVerticalGroup(
            case_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, case_headLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        case_name.setBackground(new java.awt.Color(204, 204, 204));

        champ_prenom.setBackground(new java.awt.Color(204, 204, 204));
        champ_prenom.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        champ_prenom.setText("Last Name");

        champ_user.setBackground(new java.awt.Color(204, 204, 204));
        champ_user.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        champ_user.setText("UserName");

        champ_password.setBackground(new java.awt.Color(204, 204, 204));
        champ_password.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        champ_password.setText("Password");

        champ_conf_pass.setBackground(new java.awt.Color(204, 204, 204));
        champ_conf_pass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        champ_conf_pass.setText("Retype pass");

        champ_name.setBackground(new java.awt.Color(204, 204, 204));
        champ_name.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        champ_name.setText("First Name");

        case_names.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case_namesActionPerformed(evt);
            }
        });

        case_pass_confir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case_pass_confirActionPerformed(evt);
            }
        });

        case_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case_userActionPerformed(evt);
            }
        });

        compte_creat.setBackground(new java.awt.Color(153, 0, 153));
        compte_creat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        compte_creat.setForeground(new java.awt.Color(255, 255, 255));
        compte_creat.setText("Create account");
        compte_creat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compte_creatActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login.png"))); // NOI18N

        javax.swing.GroupLayout case_nameLayout = new javax.swing.GroupLayout(case_name);
        case_name.setLayout(case_nameLayout);
        case_nameLayout.setHorizontalGroup(
            case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(case_nameLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(champ_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(champ_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(champ_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(champ_name, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(champ_conf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(case_nameLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(compte_creat, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(case_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addComponent(case_user, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(case_prenom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(case_names, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(case_pass_confir)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        case_nameLayout.setVerticalGroup(
            case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(case_nameLayout.createSequentialGroup()
                .addGroup(case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(case_names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champ_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(case_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(champ_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(champ_user, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(case_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(champ_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(case_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(case_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(champ_conf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(case_pass_confir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compte_creat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(case_head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(case_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 383, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(case_head, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(case_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void case_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case_userActionPerformed

    private void case_pass_confirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case_pass_confirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case_pass_confirActionPerformed

    private void case_namesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case_namesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case_namesActionPerformed

    private void compte_creatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compte_creatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compte_creatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel case_head;
    private javax.swing.JPanel case_name;
    private javax.swing.JTextField case_names;
    private javax.swing.JTextField case_pass_confir;
    private javax.swing.JTextField case_password;
    private javax.swing.JTextField case_prenom;
    private javax.swing.JTextField case_user;
    private javax.swing.JLabel champ_conf_pass;
    private javax.swing.JLabel champ_name;
    private javax.swing.JLabel champ_password;
    private javax.swing.JLabel champ_prenom;
    private javax.swing.JLabel champ_user;
    private javax.swing.JButton compte_creat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
